import { BASE_URL, URL_EXPIRY_TIME_MS } from "../app.js";
import { UrlModel } from "../services/database.service.js";

/**
 * Creates a new url entry in the database and sets
 * the expiry date set to 24 hours from now
 * url id is generated by changing _id to base 64
 **/
export const generateUrl = async (url: string): Promise<string> => {
  if (!URL.canParse(url)) {
    url = "https://" + url;
    if (!URL.canParse(url)) throw new Error("InvalidUrlError");
  }
  const { _id } = await UrlModel.create({
    url,
    noOfVisits: 0,
    expiry: URL_EXPIRY_TIME_MS,
  });

  return `${BASE_URL}/u/${Buffer.from(_id.toString(), "hex").toString(
    "base64url"
  )}`;
};
